### ISSUE TITLE
Differentiate between per-PR failures vs nightly smoke test runs

### ISSUE THREAD

**Issue by OliviaLynn** [lincc-frameworks/lf-workflow-dash#12]

**Comment by delucchi-cmu** [comment]
![PXL_20231024_184126913](https://github.com/lincc-frameworks/lf-workflow-dash/assets/113376043/0938b3f1-862a-4503-b3ce-86920b7faddb)

I'd suggest making the display more tabular, like in the attached image.

- One row per project
- Columns for the types of runs (make the nightly tests the first column, since that's what we generally care most about)
- Have a catch-call column at the end for any additional builds you're tracking
- Optionally put projects with any failing builds at the top of the table?

**Comment by delucchi-cmu** [comment]
![Screenshot 2023-11-02 103736](https://github.com/lincc-frameworks/lf-workflow-dash/assets/113376043/aa6ed61f-b30e-4b3a-bb31-051c1fcce8cf)

Slightly nicer image, based on prototyping work in the delucchi/jinja branch.

**Comment by OliviaLynn** [comment]
Adding a reference to #14 which added this in, and perhaps #5 can shuffle things so that this table view becomes the main/only view of the dashboard

**Comment by delucchi-cmu** [comment]
Closed by https://github.com/lincc-frameworks/lf-workflow-dash/pull/17
