### ISSUE TITLE
Auto-updater should not push html directly to main

### ISSUE THREAD

**Issue by OliviaLynn** [lincc-frameworks/lf-workflow-dash#21]

**Comment by OliviaLynn** [comment]
Fixed with https://github.com/lincc-frameworks/lf-workflow-dash/commit/9bb7179526da7913dc96737ce444d2307b9ee388

**Comment by OliviaLynn** [comment]
A follow up added in #23

**Comment by delucchi-cmu** [comment]
I think this could be addressed by pushing the html changes to a branch, instead of main (and it might clean up some other stuff too?). 

This is how the asv dashboards are generated: the workflow makes changes to a `gh-pages` branch, and the github pages configuration is changed to pull from that branch, instead of main. It overwrites all of the contents of the repo in the branch, so it's just hosting the html and other site assets.

https://github.com/astronomy-commons/hipscat/tree/gh-pages

**Comment by OliviaLynn** [comment]
Yeah; protecting our main branch does mean we'll have to change the auto updater. That sounds like a good approach!

**Comment by delucchi-cmu** [comment]
I've changed the pages setting to point to the `gh-pages` branch, which only hosts the pages content:

https://github.com/lincc-frameworks/lf-workflow-dash/tree/gh-pages

The "Update dashboard html" workflow is running without any errors and is updating the html content.

Also, now the history on `main` should reflect real development work on the dashboard code! Which is pretty nifty!
